version: "3"
services:
  geth-dev-miner-1:
    hostname: geth-dev-miner-1
    environment:
      - address=0x31B3198e314d450eF30527806c6FE9fAfFc310e5 #derived from the private key which is passed in the args
      - bootnodeId=enr:-KO4QMXcrXobuLS0b8Rz8UjPY1P9lE6UhKLNWBwJp2ujNncvN_YSYVTyCTB_2Co37hcPBIXbV4FCJqzrXIKQq0WFFAWGAYT2lWxQg2V0aMfGhNY4HfiAgmlkgnY0gmlwhKdj7-OJc2VjcDI1NmsxoQPmYjG9YnddkzcRddxsVNqDB7j1eDkfcwERgj7SXf_xIoRzbmFwwIN0Y3CCf5yDdWRwgn-c #derived from the nodekeyhex of the bootnode
      - bootnodeIp=167.99.239.227
    build:
      context: .
      dockerfile: ./minerdeploy/Dockerfile
      args:
        privatekey: e1c6283aba81d01b3a-dummy-1782d0f5c4b7d385489d83833f6fe08e46ed #replace it with your private key associated with the wallet address provided above
        password: 12337678
    ports:
      - 8546:8545
    container_name: geth-miner-1
    volumes:
      - eth-data-1:/root/.ethash
    networks:
      chainnet:
        ipv4_address: 172.25.0.102 # The monitor needs to know this address
    healthcheck:
      test: wget http://localhost:8546
      interval: 2s
      timeout: 5s
      retries: 30
networks:
  chainnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  eth-data-1:
